### ISSUE TITLE
get AI Thinker AudioKIT with ES8388 working

### ISSUE THREAD

**Issue by HeikoGr** [feelfreelinux/euphonium#1]
i did not manage to get the AudioKIT board working.

i tried to alter the i2s adress to 0x20 (as on my cspot driver) and adjust the gpios.
i was not able to make ES8388 an option in the dropdown selector, so i even manipulate the AC101 driver (file) to match my ES8388 driver file content. without success. I don't know what else i could do with my limited capabilities.

**Comment by feelfreelinux** [comment]
Hi. The I2S driver shifts the address by << 1, therefore in the berry part of the driver, the address still should be 0x10 `(0x10 << 1 == 0x20)`. You most likely only need to change the pin definitions. Feel free to reach out to me on any communicator, I would love to debug this further :)

**Comment by HeikoGr** [comment]
ok, i changed my files again back to 0x10. no i need to wait till github is ready...

 (i managed to make your code working in idf 4.3 - i can't install idf 4.4 on wsl2 under windows. But no the web part didn't compile ... so i'm stuck with the github actions...)

i sent you a friend request on discord

**Comment by HeikoGr** [comment]
it works
