### ISSUE TITLE
Littlefs not building

### ISSUE THREAD

**Issue by shark8594** [feelfreelinux/euphonium#14]
Hi,

The managed components do not seem like they are part of the Cmakelists, causing the cmake to fail:

:/Users/abhin/esp/components/wear_levelling C:/Users/abhin/esp/components/wifi_provisioning C:/Users/abhin/esp/components/wpa_supplicant C:/Users/abhin/esp/components/xtensa
CMake Error at CMakeLists.txt:10 (littlefs_create_partition_image):
  Unknown CMake command "littlefs_create_partition_image".

-- Configuring incomplete, errors occurred!

Can be fixed by by moving it under components or using add_subdirectory(). 

PS it is a pain to build esp_littlefs on windows.

Thanks!

**Comment by HeikoGr** [comment]
I managed to build euphonium with the use of WSL2 this way:
https://github.com/HeikoGr/euphonium/wiki/using-Windows-Subsystem-for-Linux-(WSL)-for-compilation

it‘s way easier then setup a Windows only toolchain…

**Comment by shark8594** [comment]
Thanks for the steps, works in ubuntu.
