### ISSUE TITLE
Buffering changes

### ISSUE THREAD

**Issue by shark8594** [feelfreelinux/euphonium#19]
Hi,

Have been testing out euphonium with a custom audio board (ES8388) and it works great!. In the previous spotify stand alone version cspot, I could tweak the buffer size and logic in ChunkedAudioStream (BUFFER_SIZE), however in the current project seems like it is moved to ChunkedByteStream? Any clues on how to change the buffer size and add logic? . loadAheadEnabled flag only loads one extra chuck right? Also, I observed a segfault when we skip/seek tracks on spotify. 

Thanks!

**Comment by feelfreelinux** [comment]
Cspot crashes are currently being worked on, current master is not really stable in that regard :). Euphonium has it's buffer defined in `MainAudioBuffer.h`

**Comment by shark8594** [comment]
Thanks :), I tried it and seems like the change is taking effect:
![image](https://user-images.githubusercontent.com/76969542/150657775-a77ef5ac-94d4-4b09-bdbf-617910278467.png)
