### ISSUE TITLE
Android app build fail

### ISSUE THREAD

**Issue by shark8594** [feelfreelinux/euphonium#21]
Hi,

Seems like the app is missing some sub-modules and the build is failing.  Error below:

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Workspace\euphonium_tip\euphonium\app\android\app\capacitor.build.gradle' line: 10

* What went wrong:
A problem occurred evaluating script.
> Could not read script 'C:\Workspace\euphonium_tip\euphonium\app\android\capacitor-cordova-android-plugins\cordova.variables.gradle' as it does not exist.

Help greatly appreciated :)

Thanks!

**Comment by shark8594** [comment]
Adding this resolved it:

npx cap add android 

Thanks!

**Comment by danielehrhardt** [comment]
You also can download the apk here:
https://github.com/feelfreelinux/euphonium/actions/runs/1836786181

**Comment by shark8594** [comment]
Thanks, great work!
