### ISSUE TITLE
Use of `sdt::move()` means that only one event listener can subscribe to an EventBus

### ISSUE THREAD

**Issue by jdthorpe** [feelfreelinux/euphonium#60]
Not sure if this is a feature, quirk, or an error, but the use of `std::move()` in [this line](https://github.com/feelfreelinux/euphonium/blob/e562fea1a8eb659e9cba97820036f6208b2aec34/euphonium/src/EventBus.cpp#L23) means only one event subscriber can subscribe to an EventBus...

**Comment by alufers** [comment]
Yeah, it should be a reference

**Comment by feelfreelinux** [comment]
Correct, I'll adjust it shortly.
